Repository sipe-team/3-2_smart_fintech, pull requests merged in 2025-01, with the labels that each got.

#4 [Chore]: ktlint 적용
  .editorconfig
  build.gradle.kts
  scripts/pre-commit
  src/test/kotlin/tech/sipe/fintech/FintechApplicationTests.kt
Labels: code

#5 docs: 리드미를 작성한다.
  README.md
Labels: log

#10 [윤한] Spring modulith 실습
  build.gradle.kts
  src/main/kotlin/tech/sipe/fintech/account/Account.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountApi.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountEntity.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountRepository.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountService.kt
  src/main/kotlin/tech/sipe/fintech/payment/Payment.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentApi.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentEntity.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentService.kt
  src/main/kotlin/tech/sipe/fintech/transfer/Transfer.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferApi.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferEntity.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferService.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWallet.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWalletEntity.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWalletJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWalletRepository.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWalletService.kt
Labels: idea

#19 refactor: ktlint versioning by kotlin 2.1.0
  .editorconfig
  build.gradle.kts
  src/main/kotlin/tech/sipe/fintech/account/Account.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountApi.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountEntity.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountRepository.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountService.kt
  src/main/kotlin/tech/sipe/fintech/common/LoggerUtil.kt
  src/main/kotlin/tech/sipe/fintech/payment/Payment.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentApi.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentEntity.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentService.kt
  src/main/kotlin/tech/sipe/fintech/payment/package-info.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/Transfer.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferApi.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferEntity.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferService.kt
  src/main/kotlin/tech/sipe/fintech/wallet/PayWalletApi.kt
  src/main/kotlin/tech/sipe/fintech/wallet/WalletModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/domain/PayWallet.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/domain/PayWalletMapper.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/domain/PayWalletRepository.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/domain/WalletStatus.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/infra/PayWalletEntity.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/infra/PayWalletJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/infra/PayWalletRepositoryImpl.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/presentation/PayWalletApiImpl.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/service/PayWalletService.kt
  src/test/kotlin/tech/sipe/fintech/FintechApplicationTests.kt
Labels: code

#15 docs: README 목차 정리 및 내용 업데이트
  README.md
Labels: log

#22 [Refactor]: Gradle version catalog
  build.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  libs.versions.toml
Labels: code

#21 [Refactor]: logger Extension
  src/main/kotlin/tech/sipe/fintech/common/LoggerExtension.kt
  src/main/kotlin/tech/sipe/fintech/common/LoggerUtil.kt
Labels: code

#20 [Chore]: Global Response Exception Advice
  src/main/kotlin/tech/sipe/fintech/global/common/GlobalResponse.kt
  src/main/kotlin/tech/sipe/fintech/global/common/GlobalResponseAdvice.kt
  src/main/kotlin/tech/sipe/fintech/global/config/DatasourceConfiguration.kt
  src/main/kotlin/tech/sipe/fintech/global/error/CustomException.kt
  src/main/kotlin/tech/sipe/fintech/global/error/ErrorCode.kt
  src/main/kotlin/tech/sipe/fintech/global/error/ErrorResponse.kt
  src/main/kotlin/tech/sipe/fintech/global/error/GlobalExceptionHandler.kt
Labels: code

#23 [Feature] TransferEntity 정의
  src/main/kotlin/tech/sipe/fintech/common/Currency.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/Transfer.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferEntity.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/TransferRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/Transfer.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferService.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferStatus.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferType.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/infra/entity/TransferEntity.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/infra/jpa/TransferJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/presentation/TransferApi.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/domain/PayWallet.kt
  src/main/kotlin/tech/sipe/fintech/wallet/internal/infra/PayWalletEntity.kt
Labels: code

#28 feat: 결제 기능 구현
  src/main/kotlin/tech/sipe/fintech/global/GlobalModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/payment/Payment.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentApi.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentEntity.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/payment/PaymentService.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/domain/Payment.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/domain/PaymentMethod.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/domain/PaymentRepository.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/domain/PaymentStatus.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/infra/PaymentRepositoryAdapter.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/infra/entity/PaymentEntity.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/infra/entity/PaymentEntityMapper.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/infra/jpa/PaymentJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/presentation/PaymentApi.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/presentation/dto/PaymentRequest.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/presentation/dto/PaymentResponse.kt
  src/main/kotlin/tech/sipe/fintech/payment/internal/service/PaymentService.kt
  src/main/kotlin/tech/sipe/fintech/transfer/TransferModuleMetadata.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/presentation/TransferApi.kt
  src/main/kotlin/tech/sipe/fintech/wallet/WalletModuleMetadata.kt
Labels: code

#29 [Feat]: 송금 로직 추가
  src/main/kotlin/tech/sipe/fintech/external/ExternalTransferApi.kt
  src/main/kotlin/tech/sipe/fintech/external/service/ExternalTransferApiImpl.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/Transfer.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferRepository.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/domain/TransferService.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/infra/TransferMapper.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/infra/jpa/TransferRepositoryImpl.kt
  src/main/kotlin/tech/sipe/fintech/transfer/internal/presentation/TransferApi.kt
  src/main/kotlin/tech/sipe/fintech/wallet/domain/PayWalletTransferredEvent.kt
  src/main/kotlin/tech/sipe/fintech/wallet/service/PayWalletService.kt
Labels: code

#26 [FEAT] week4/sangjun account 모듈 구현
  src/main/kotlin/tech/sipe/fintech/account/Account.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountApi.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountEntity.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountInternalApi.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountRepository.kt
  src/main/kotlin/tech/sipe/fintech/account/AccountService.kt
  src/main/kotlin/tech/sipe/fintech/account/domain/Account.kt
  src/main/kotlin/tech/sipe/fintech/account/domain/AccountRepository.kt
  src/main/kotlin/tech/sipe/fintech/account/domain/BankName.kt
  src/main/kotlin/tech/sipe/fintech/account/infra/AccountEntity.kt
  src/main/kotlin/tech/sipe/fintech/account/infra/AccountJpaRepository.kt
  src/main/kotlin/tech/sipe/fintech/account/infra/AccountMapper.kt
  src/main/kotlin/tech/sipe/fintech/account/infra/AccountRepositoryImpl.kt
  src/main/kotlin/tech/sipe/fintech/account/presentation/AccountExternalApi.kt
  src/main/kotlin/tech/sipe/fintech/account/presentation/AccountInternalApiImpl.kt
  src/main/kotlin/tech/sipe/fintech/account/presentation/request/CreateAccountRequest.kt
  src/main/kotlin/tech/sipe/fintech/account/presentation/response/GetAccountResponse.kt
  src/main/kotlin/tech/sipe/fintech/account/service/AccountService.kt
  src/main/kotlin/tech/sipe/fintech/common/BaseEntity.kt
  src/main/kotlin/tech/sipe/fintech/global/error/ErrorCode.kt
Labels: code

#31 docs: 프로젝트 회고에 대한 내용 추가
  README.md
Labels: log
